apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0.3
spec:
  releaseName: plex
  chart:
    git: https://github.com/munnerz/kube-plex
    path: charts/kube-plex
    ref: master
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.16.0.1226-7eb2c8f6f
      pullPolicy: IfNotPresent
    claimToken: claim--JymMx6oxPMEuz1wsAzY
    persistence:
      data:
        claimName: k3s-plex-data
      config:
        claimName: k3s-plex-config
      transcode:
        claimName: k3s-plex-transcode
    ingress:
      enabled: true
      annotations:
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      tls:
        - hosts: 
          - plex.apps.dmacneil.co.uk
          secretName: plex-tls

