apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0.3
spec:
  releaseName: plex
  chart:
    git: https://github.com/munnerz/kube-plex
    path: charts/kube-plex
    ref: master
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.16.0.1226-7eb2c8f6f
      pullPolicy: IfNotPresent
    claimToken: claim-b46kNjYaLvS8B9yTnpWs
    persistence:
      data:
        claimName: k3s-plex-data
      config:
        claimName: k3s-plex-config
      transcode:
        claimName: k3s-plex-transcode
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: traefik
      tls:
      - hosts: 
        - plex.apps.dmacneil.co.uk
        - plex.home.int
        secretName: plex-tls
      hosts:
      - plex.apps.dmacneil.co.uk
      - plex.home.int
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-node-01.home.int
                - k3s-node-02.home.int
                - k3s-node-03.home.int

