apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: consul
  namespace: vault
  annotations:
    fluxcd.io/ignore: true
spec:
  releaseName: consul
  chart:
    git: https://github.com/hashicorp/consul-helm
    ref: master
    path: .
  values:
    global:
      enabled: true
      image: "consul:1.6.1"
