---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: vault
  chart:
    repository: https://kubernetes-charts.banzaicloud.com
    name: banzaicloud-stable/vault
    version: 0.8.3
  values:
    enabled: true
    replicCount: 3
    image:
      repository: "vault:1.3.0-beta1"
    ingress:
      enabled: true
    hosts:
    - vault.apps.dmacneil.co.uk
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    tls:
      #Secrets must be manually created in the namespace.
    - secretName: vault-tls
      hosts:
      - vault.apps.dmacneil.co.uk
    persistence:
      enabled: true
      storageClass: nfs-client
      size: 1G
    config:
      listener:
        tcp:
          tls_disable: 1
          address: "[::]:8200"
          clusterAdress: "[::]:8200"
          tls_cert_file: /vault/tls/server.crt
          tls_key_file: /vault/tls/server.key
      storage:
        consul:
          path: "vault/"
          address: "consul-consul-server:8500"
      telemtry:
        statsd_address: localhost:9125
      ui: true
    externalConfig:
      policies:
      - name: allow_secrets
        rules: path "secret/*" { capabilities = ["create", "read", "update", "delete",
          "list"] }
      auth:
      - type: kubernetes
        roles:
            # Allow ever pod in the default namespace to use secret kv store
        - name: default
          bound_service_account_names: ["vault"]
          bound_service_account_namespaces: ["vault"]
          policies: allow_secrets
          ttl: 1h
      secrets:
      - path: secret
        type: kv
        description: General secrets
        options:
          version: 2
