apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  chart:
    git: https://github.com/hashicorp/vault-helm
    ref: master
    path: .
  values:
    global:
      enabled: true
      image: "vault:1.2.3"
    server:
      extraSecretEnvironmentVars:
        - envName: AWS_ACCESS_KEY_ID
          secretName: eks-creds
          secretKey: AWS_ACCESS_KEY_ID
        - envName: AWS_SECRET_ACCESS_KEY
          secretName: eks-creds
          secretKey: AWS_SECRET_ACCESS_KEY
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: gp2
      ha:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          seal "awskms" {
            region     = "eu-west-1"
            kms_key_id = "01ba51dd-6519-4e85-807d-5e755fbdfd4f"
          }
          storage "consul" {
            path = "vault"
            address = "consul-consul-server:8500"
          }
      ui:
        enabled: true
      ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          hosts:
            - host: vault.apps.dmacneil.co.uk
              paths: ["/"]
