apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vault-tokenreview-binding
  namespace: vault # Change it if you don't use the defaults when you install it via Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-vault-secrets-webhook # Change it if you don't use the defaults when you install it via Helm
  namespace: vault # Change it if you don't use the defaults when you install it via Helm

